### ISSUE TITLE
debug_file function doesn't work

### ISSUE THREAD

**Issue by hilaladdiyar** [calibreworks/calibrefx#103]
debug_file doesn't work because there is an error when initializing global $wp_filesystem.

This is happened because 'request_filesystem_credentials()' function isn't available until AFTER wp_loaded action hook. https://codex.wordpress.org/Filesystem_API#Tips_and_Tricks

**Comment by ivankristianto** [comment]
yes i notice that. do you have any solution?

**Comment by hilaladdiyar** [comment]
How about we use file_put_contents()? so we don't have to use $wp_filesystem
