### ISSUE TITLE
Header Image Not Showing Fresh Installation

### ISSUE THREAD

**Issue by am-sultan** [calibreworks/calibrefx#45]
Header image is not showing.

**Comment by hilaladdiyar** [comment]
You can show the default header image by unchecking 'Show header text with your image.' option on custom header settings (Appearance > Header).

![image](https://cloud.githubusercontent.com/assets/1925679/6250199/dc377358-b7be-11e4-9802-fa1aa8030a96.png)

**Comment by ivankristianto** [comment]
I tried with WP 4.1.1
so when you click appearances > header, it take you to cusotmizer page. and it doesn't work from there.

**Comment by ivankristianto** [comment]
Bugs Fixed
