### ISSUE TITLE
Couple Bugs in 2.0.1

### ISSUE THREAD

**Issue by hilaladdiyar** [calibreworks/calibrefx#66]
After I upgraded into version 2.0.1, there are couple fatal error bugs

![image](https://cloud.githubusercontent.com/assets/1925679/6538916/4f51ab18-c49b-11e4-8df0-a895a99f1c8d.png)

![image](https://cloud.githubusercontent.com/assets/1925679/6538936/8d13f578-c49b-11e4-9459-d54d95fd09fc.png)

![image](https://cloud.githubusercontent.com/assets/1925679/6539055/beeb5436-c49d-11e4-8046-13ceede0fe1d.png)

![image](https://cloud.githubusercontent.com/assets/1925679/6539115/12bbe872-c49f-11e4-9fd4-adfdcca40f7e.png)

**Comment by hilaladdiyar** [comment]
Pak @ivankristianto please review my bug fixes

**Comment by ivankristianto** [comment]
Yes this is because PHP 5.4 incompatibility, will check this soon.

**Comment by ivankristianto** [comment]
@hilaladdiyar please do pull request.
