### ISSUE TITLE
Error on Footer section when not in singuar page

### ISSUE THREAD

**Issue by sofyansitorus** [calibreworks/calibrefx#96]
Bug found on footer-hook.php line 125.

function calibrefx_add_socials_script() {
	global $post;

	if ( is_active_widget( false, false, 'facebook-comment-widget' ) OR
		is_active_widget( false, false, 'facebook-likebox-widget' ) ) {
		echo
			'<div id="fb-root"></div>
			<script>(function(d, s, id) {
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) return;
			  js = d.createElement(s); js.id = id;
			  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.3&appId=111504338957832";
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, \'script\', \'facebook-jssdk\'));</script>'."\n";
	}

	if ( is_active_widget( false, false, 'twitter-timeline-widget' ) ) {
		echo
			'<script>
			window.twttr = (function (d,s,id) {
			var t, js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id) ) return; js=d.createElement(s); js.id=id;
			js.src="https://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
			return window.twttr || (t = { _e: [], ready: function(f) { t._e.push(f) } });
			}(document, "script", "twitter-wjs") );
			</script>'."\n";
	}

	if ( $post && has_shortcode( get_the_content( ), 'gplus' ) ){
		echo
			'<script type="text/javascript">
			  (function() {
				var po = document.createElement(\'script\'); po.type = \'text/javascript\'; po.async = true;
				po.src = \'https://apis.google.com/js/plusone.js?onload=onLoadCallback\';
				var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(po, s);
			  })();
			</script>'."\n";
	}

}

**Comment by ivankristianto** [comment]
fixed in #1adc2e0adfb8fc3c37d7ff45369b098e69fff946
